version: '3.1'
services:
  app:
    container_name: svc-playerdb
    image: svc-playerdb
    build: ./
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
